version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../backend/foodgram/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: tetrapack55/foodgram_backend
    env_file: ../backend/foodgram/.env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: tetrapack55/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: tetrapack55/foodgram_nginx
    ports:
      - "8888:80"
    volumes:
      - static:/static
      - media:/app/media/
    depends_on:
      - backend
